
// This file has been generated by the GUI designer. Do not modify.
namespace Orange
{
	public partial class MainDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Table table1;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.FileChooserButton ProjectFolderChooser;
		private global::Gtk.ComboBox TargetPlatform;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView CompileLog;
		private global::Gtk.Button RunButton;
		private global::Gtk.Button CleanButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Orange.MainDialog
			this.Name = "Orange.MainDialog";
			this.Title = "Orange";
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			// Internal child Orange.MainDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(4));
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = "Project folder";
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = "Target platform";
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ProjectFolderChooser = new global::Gtk.FileChooserButton ("Select A Project Folder", ((global::Gtk.FileChooserAction)(2)));
			this.ProjectFolderChooser.Name = "ProjectFolderChooser";
			this.ProjectFolderChooser.ShowHidden = true;
			this.table1.Add (this.ProjectFolderChooser);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.ProjectFolderChooser]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.TargetPlatform = global::Gtk.ComboBox.NewText ();
			this.TargetPlatform.AppendText ("Desktop (PC, Mac, Linux)");
			this.TargetPlatform.AppendText ("iPhone/iPad");
			this.TargetPlatform.Name = "TargetPlatform";
			this.TargetPlatform.Active = 0;
			this.table1.Add (this.TargetPlatform);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.TargetPlatform]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.CompileLog = new global::Gtk.TextView ();
			this.CompileLog.CanFocus = true;
			this.CompileLog.Name = "CompileLog";
			this.CompileLog.Editable = false;
			this.CompileLog.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.CompileLog);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w8.Position = 1;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w9.Position = 0;
			// Internal child Orange.MainDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.RunButton = new global::Gtk.Button ();
			this.RunButton.CanDefault = true;
			this.RunButton.CanFocus = true;
			this.RunButton.Name = "RunButton";
			this.RunButton.UseUnderline = true;
			this.RunButton.Label = "Run";
			w10.Add (this.RunButton);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.RunButton]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CleanButton = new global::Gtk.Button ();
			this.CleanButton.CanFocus = true;
			this.CleanButton.Name = "CleanButton";
			this.CleanButton.UseUnderline = true;
			this.CleanButton.Label = "Clean";
			w10.Add (this.CleanButton);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.CleanButton]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 572;
			this.DefaultHeight = 493;
			this.RunButton.HasDefault = true;
			this.Show ();
			this.RunButton.Clicked += new global::System.EventHandler (this.OnRunClicked);
			this.CleanButton.Clicked += new global::System.EventHandler (this.OnCleanButtonClicked);
		}
	}
}
