
// This file has been generated by the GUI designer. Do not modify.
namespace Orange
{
	public partial class MainDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Table table1;
		private global::Gtk.FileChooserButton AssetsFolderChooser;
		private global::Gtk.FileChooserButton GameAssemblyChooser;
		private global::Gtk.FileChooserButton GameProtoChooser;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.ComboBox TargetPlatform;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView CompileLog;
		private global::Gtk.Button SyncButton;
		private global::Gtk.Button RebuildButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Orange.MainDialog
			this.Name = "Orange.MainDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Orange");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			// Internal child Orange.MainDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(4));
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.AssetsFolderChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select An Assets Folder"), ((global::Gtk.FileChooserAction)(2)));
			this.AssetsFolderChooser.Name = "AssetsFolderChooser";
			this.AssetsFolderChooser.ShowHidden = true;
			this.table1.Add (this.AssetsFolderChooser);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.AssetsFolderChooser]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GameAssemblyChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select An Assembly"), ((global::Gtk.FileChooserAction)(0)));
			this.GameAssemblyChooser.Name = "GameAssemblyChooser";
			this.table1.Add (this.GameAssemblyChooser);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.GameAssemblyChooser]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GameProtoChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select The Game .proto File"), ((global::Gtk.FileChooserAction)(0)));
			this.GameProtoChooser.Name = "GameProtoChooser";
			this.table1.Add (this.GameProtoChooser);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.GameProtoChooser]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Assets directory");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Target platform");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Game assembly");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Game .proto");
			this.label4.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.TargetPlatform = global::Gtk.ComboBox.NewText ();
			this.TargetPlatform.AppendText (global::Mono.Unix.Catalog.GetString ("Desktop (PC, Mac, Linux)"));
			this.TargetPlatform.AppendText (global::Mono.Unix.Catalog.GetString ("iPhone/iPad"));
			this.TargetPlatform.Name = "TargetPlatform";
			this.TargetPlatform.Active = 0;
			this.table1.Add (this.TargetPlatform);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.TargetPlatform]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.CompileLog = new global::Gtk.TextView ();
			this.CompileLog.CanFocus = true;
			this.CompileLog.Name = "CompileLog";
			this.CompileLog.Editable = false;
			this.CompileLog.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.CompileLog);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w12.Position = 1;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w13.Position = 0;
			// Internal child Orange.MainDialog.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.SyncButton = new global::Gtk.Button ();
			this.SyncButton.CanDefault = true;
			this.SyncButton.CanFocus = true;
			this.SyncButton.Name = "SyncButton";
			this.SyncButton.UseUnderline = true;
			this.SyncButton.Label = global::Mono.Unix.Catalog.GetString ("Synchronize");
			w14.Add (this.SyncButton);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.SyncButton]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.RebuildButton = new global::Gtk.Button ();
			this.RebuildButton.CanFocus = true;
			this.RebuildButton.Name = "RebuildButton";
			this.RebuildButton.UseUnderline = true;
			this.RebuildButton.Label = global::Mono.Unix.Catalog.GetString ("Rebuild");
			w14.Add (this.RebuildButton);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.RebuildButton]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 623;
			this.DefaultHeight = 467;
			this.SyncButton.HasDefault = true;
			this.Show ();
			this.SyncButton.Clicked += new global::System.EventHandler (this.OnSyncClicked);
			this.RebuildButton.Clicked += new global::System.EventHandler (this.OnRebuildButtonClicked);
		}
	}
}
